In [1]:
import pandas as pd

# Read a sample of the data
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/'
df = pd.read_csv(prefix + 'yellow_tripdata_2021-01.csv.gz', nrows=100)

# Display first rows
df.head()

# Check data types
df.dtypes

# Check data shape
df.shape

(100, 18)

In [2]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [3]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(
    prefix + 'yellow_tripdata_2021-01.csv.gz',
    nrows=100,
    dtype=dtype,
    parse_dates=parse_dates
)

In [4]:
df.dtypes
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [5]:
!uv add sqlalchemy "psycopg[binary,pool]"

Resolved 109 packages in 0.76ms
Checked 13 packages in 0.21ms

In [6]:
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg://root:root@localhost:8888/ny_taxi')

In [7]:
!uv add psycopg2-binary

Resolved 109 packages in 1ms
Checked 13 packages in 0.29ms

In [8]:
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg://root:root@localhost:5432/ny_taxi')

In [9]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [11]:
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [14]:
df_iter = pd.read_csv(
    prefix + 'yellow_tripdata_2021-01.csv.gz',
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000
)

In [17]:
for df_chunk in df_iter:
    print(len(df_chunk))

100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
69765

In [18]:
df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

-1

In [19]:
df_chunk.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
1300000,<NA>,2021-01-05 10:38:40,2021-01-05 10:46:20,<NA>,1.30,<NA>,<NA>,170,161,<NA>,7.00,0.0,0.5,1.03,0.00,0.3,11.33,2.5
1300001,<NA>,2021-01-05 10:17:14,2021-01-05 10:41:21,<NA>,7.90,<NA>,<NA>,216,198,<NA>,31.49,0.0,0.5,2.75,0.00,0.3,35.04,0.0
1300002,<NA>,2021-01-05 10:39:00,2021-01-05 10:46:00,<NA>,0.98,<NA>,<NA>,62,62,<NA>,16.23,0.0,0.5,2.75,0.00,0.3,19.78,0.0
1300003,<NA>,2021-01-05 10:05:00,2021-01-05 10:19:00,<NA>,1.59,<NA>,<NA>,85,71,<NA>,13.45,0.0,0.5,2.75,0.00,0.3,17.00,0.0
1300004,<NA>,2021-01-05 10:18:08,2021-01-05 10:41:40,<NA>,9.87,<NA>,<NA>,236,208,<NA>,30.23,0.0,0.5,2.75,6.12,0.3,39.90,0.0

In [20]:
first = True

for df_chunk in df_iter:

    if first:
        # Create table schema (no data)
        df_chunk.head(0).to_sql(
            name="yellow_taxi_data",
            con=engine,
            if_exists="replace"
        )
        first = False
        print("Table created")

    # Insert chunk
    df_chunk.to_sql(
        name="yellow_taxi_data",
        con=engine,
        if_exists="append"
    )

    print("Inserted:", len(df_chunk))

## Alternative way to ingest the data in the database table.

In [24]:
# first_chunk = next(df_iter)

# first_chunk.head(0).to_sql(
#     name="yellow_taxi_data",
#     con=engine,
#     if_exists="replace"
# )

# print("Table created")

# first_chunk.to_sql(
#     name="yellow_taxi_data",
#     con=engine,
#     if_exists="append"
# )

# print("Inserted first chunk:", len(first_chunk))

# for df_chunk in df_iter:
#     df_chunk.to_sql(
#         name="yellow_taxi_data",
#         con=engine,
#         if_exists="append"
#     )
#     print("Inserted chunk:", len(df_chunk))

In [27]:
!uv add tqdm

Resolved 110 packages in 312ms
Prepared 2 packages in 49ms
Uninstalled 1 package in 0.70ms
░░░░░░░░░░░░░░░░░░░░ [0/2] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 2 packages in 9ms
 ~ pipeline==0.1.0 (from file:///workspaces/docker-workshop/pipeline)
 + tqdm==4.70.1

In [28]:
from tqdm.auto import tqdm

for df_chunk in tqdm(df_iter):
    ...

0it [00:00, ?it/s]

In [31]:
!uv add pgcli

Resolved 119 packages in 300ms
Prepared 10 packages in 30ms
Uninstalled 1 package in 0.69ms
░░░░░░░░░░░░░░░░░░░░ [0/10] Installing wheels...                                warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 10 packages in 26ms
 + cli-helpers==2.15.1
 + click==8.5.0
 + configobj==5.0.9
 + pgcli==4.7.0
 + pgspecial==2.2.1
 ~ pipeline==0.1.0 (from file:///workspaces/docker-workshop/pipeline)
 + setproctitle==1.3.7
 + sqlparse==0.6.0
 + tabulate==0.10.0
 + tzlocal==5.4.4

In [ ]:
!uv run pgcli -h localhost -p 5432 -u root -d ny_taxi